CREATE TABLE IF NOT EXISTS movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    genre VARCHAR(100) NOT NULL,
    duration INT NOT NULL,
    rating REAL NOT NULL,
    release_year INT NOT NULL
);

CREATE TABLE IF NOT EXISTS showtime (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    price REAL NOT NULL,
    theater VARCHAR(100) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_showtime_movie FOREIGN KEY (movie_id) REFERENCES movie(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    showtime_id BIGINT NOT NULL,
    seat_number INT NOT NULL,
    user_id UUID NOT NULL,
    CONSTRAINT fk_booking_showtime FOREIGN KEY (showtime_id) REFERENCES showtime(id) ON DELETE CASCADE
);